spring:
  datasource:
    url: jdbc:mysql://localhost/ting?useSSL=false&characterEncoding=utf8
    username: root
    password: 123123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
str: aaa
